<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="chirag-inspiron3558" failures="1" tests="6" name="Default test" time="0.089" errors="0" timestamp="2021-01-10T20:02:13 IST">
  <testcase classname="TestCalculate" name="emptyStringReturnsZero" time="0.022"/>
  <testcase classname="TestCalculate" name="negativeInputReturnsException" time="0.005">
    <failure type="org.testng.TestException" message="
Method TestCalculate.negativeInputReturnsException()[pri:0, instance:TestCalculate@6a2b953e] should have thrown an exception of type class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method TestCalculate.negativeInputReturnsException()[pri:0, instance:TestCalculate@6a2b953e] should have thrown an exception of type class java.lang.Exception
at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:82)
at org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:747)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:635)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- negativeInputReturnsException -->
  <testcase classname="TestCalculate" name="singleValueIsReplied" time="0.002"/>
  <testcase classname="TestCalculate" name="threeNumbersCommaDelimitersBothWaysReturnSum" time="0.002"/>
  <testcase classname="TestCalculate" name="twoNumbersCommaDelimitersReturnSum" time="0.002"/>
  <testcase classname="TestCalculate" name="twoNumbersNewLineDelimitersReturnSum" time="0.001"/>
</testsuite> <!-- Default test -->
